In [1]:
import pandas as pd

sample_df = pd.read_csv("../data/processed/filtered_complaints.csv")

sample_df.shape

(2100, 12)

In [2]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [3]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)

In [4]:
chunks = []

for _, row in sample_df.iterrows():

    split_text = text_splitter.split_text(
        row["cleaned_text"]
    )

    for chunk in split_text:

        chunks.append({
            "complaint_id": row["complaint_id"],
            "product_category": row["product_category"],
            "chunk": chunk
        })

chunks_df = pd.DataFrame(chunks)

chunks_df.head()

,complaint_id,product_category,chunk
0,10001645,Savings Account,synchrony charged me a monthly maintenance fee...
1,10001645,Savings Account,refunded and a guarantee this will not happen ...
2,10000510,Credit Card,someone made fraudulent purchases on my chase ...
3,10000510,Credit Card,a police report and have evidence that i was i...
4,10001411,Savings Account,ally bank charged me a monthly maintenance fee...

In [5]:
chunks_df.shape

(3838, 3)

In [6]:
chunks = []

for _, row in sample_df.iterrows():

    split_text = text_splitter.split_text(row["cleaned_text"])

    for chunk in split_text:
        chunks.append({
            "complaint_id": row["complaint_id"],
            "product_category": row["product_category"],
            "chunk": chunk
        })

chunks_df = pd.DataFrame(chunks)

In [7]:
chunks_df.shape

(3838, 3)

In [8]:
chunks_df.head()

,complaint_id,product_category,chunk
0,10001645,Savings Account,synchrony charged me a monthly maintenance fee...
1,10001645,Savings Account,refunded and a guarantee this will not happen ...
2,10000510,Credit Card,someone made fraudulent purchases on my chase ...
3,10000510,Credit Card,a police report and have evidence that i was i...
4,10001411,Savings Account,ally bank charged me a monthly maintenance fee...

In [9]:
chunks_df["product_category"].value_counts()

product_category
Credit Card        1600
Savings Account    1093
Money Transfer      609
Personal Loan       536
Name: count, dtype: int64

In [10]:
chunks_df.to_csv(
    "../data/processed/chunks.csv",
    index=False
)